### ISSUE TITLE
data sort qf removes all data statements

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [fidley/ABAPQuickFix#67] opened 2024-06-17 08:38 UTC
I'm creating an old school wizard, so we have a function group, function module, top include, the usual suspects.
The top include had concatenated data statements, so first I applied the the split qf which worked ok.
Saved, activated (not really necesssary, just mentioning it).

Next I tried the "sort" qf: all the data statements are gone and the status line has this message: `Quelltext nicht formatierbar. Modularisierungseinheit nicht gefunden` (I'm logged in in German, a rough translation should be "Source text cannot be formatted. Modularization unit not found")

I'm fine with reverting the changes immediately if I notice the qf went awry, but I wonder if it could be made to work in this context or at least blocked if the fix is not possible.

**Comment by fidley** [comment] 2024-06-17 08:51
Hi Andrea, 
I will work on this today evening. Seems my last updates were solving one bug, and creating next one..
Cheers

**Comment by fidley** [comment] 2024-06-18 08:12
Damn, can you post your code here? Somehow I cannot reproduce it

**Comment by fidley** [comment] 2024-06-18 08:16
![data sort](https://github.com/fidley/ABAPQuickFix/assets/7912195/f9bd1b2f-aa3d-440e-a666-9a26f39916ee)

**Comment by AndreaBorgia-Abo** [comment] 2024-06-18 08:41
I'm not sure I can, actually, so I'll have to try and reproduce the issue at home (assuming the Wizard generator is available in one of the MiniSAPs). In the meanwhile, is there some trace that I can generate and send it over to you?

**Comment by fidley** [comment] 2024-06-18 12:16
just copy this what you selected for sorting xD and paste here.

You can also try to do again an update

**Comment by fidley** [comment] 2024-06-18 15:45
Thanks. I'm afraid I can't find the reason for your issue. Maybe it's something with the comments? 
I've pushed now some changes, so the inline comments should be at least partially handled in the sorting QF.

Or maybe @lukas-mb can help? He added this part, so maybe he had such behaviour as well?

**Comment by lukas-mb** [comment] 2024-06-19 15:07
That is strange. I can't reproduce it either...

I tested all versions 1.1.6.XXX and it works smoothly except the latest one (1.1.6.202406181410). Here I get an extra comment at the end, but the sorting still works:
![Animation](https://github.com/fidley/ABAPQuickFix/assets/147548956/4984e986-ea0d-4611-9360-c17f0707c59c)

**Comment by AndreaBorgia-Abo** [comment] 2024-06-19 19:04
Thanks for checking, seems I am the only one experiencing this issue. Is there a way to trace what is going on? Maybe writing a tracelog that I can attach?

**Comment by fidley** [comment] 2024-06-19 20:41
@lukas-mb the "last comment" bug I can see as well.... I need to rethink how to handle this.
Normally when you have the AbapStatement it begins where the previous one ends. So in the case of your example the DATA: gf_answer type C. ends at dot, while comment is assigned to next one. Normally I can change that the statement ends after the inline comment, but then all (most) exisitng quick fixes will stop to work correctly as dot or comma will be included into AbapStatement. Give me some time to fix it. I'll create a bug from it.


@AndreaBorgia-Abo  the easiest way for us to check would be if you would clone the repo into your Eclipse and then you would run it in debug mode. I could lead you through that process once you have it in your installation. Or a session with remote control could be helpful so I could see the behavior or help you to create the debug environment.

**Comment by AndreaBorgia-Abo** [comment] 2024-06-20 11:44
A Teams session would be a good idea, let me discusss this internally first then I'll get back to you.

**Comment by fidley** [comment] 2024-06-24 09:40
@lukas-mb we found the issue with @AndreaBorgia-Abo , he was using sorting of the components without opening the Preferences for it (so initial status). When doing so, there was no collection for the statements not matching the initial prefixes. 
fix will be to add empty prefix here
![image](https://github.com/fidley/ABAPQuickFix/assets/7912195/175e1d8a-f94f-45c7-a620-64a32323be59)
and here
![image](https://github.com/fidley/ABAPQuickFix/assets/7912195/feb32388-b666-443b-8584-8e61620930c1)

**Comment by fidley** [comment] 2024-06-24 09:40
Will publish it in the evening

**Comment by fidley** [comment] 2024-06-24 13:26
deployed

**Closed by fidley** 2024-06-24 13:26 UTC
Labels: bug

**Comment by lukas-mb** [comment] 2024-06-27 09:52
oh, that explains why it worked for us. Thank you for fixing!
